---
- name: Download CloudWatch Agent
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb

- name: Install CloudWatch Agent
  apt:
    deb: /tmp/amazon-cloudwatch-agent.deb

- name: Configure CloudWatch Agent
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
  notify: restart cloudwatch-agent

- name: Collectd setup (if needed for extended metrics)
  apt:
    name: collectd
    state: present
    update_cache: yes

- name: Start CloudWatch Agent
  command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
